export const HOME_DATA=[
    {
        id:1,
        classname:"one",
        name:"Model S",
        link:"/models",
        img:"https://firebasestorage.googleapis.com/v0/b/the-tesla-clone.appspot.com/o/model-s.jpg?alt=media&token=dba2362f-a922-4363-9ed7-357ac0fe4b58",
        description:"Order online for ",
        description2:"Touchless Delivery",
        leftBtnText:"Custom order",
        rightBtnText:"Existing Inventory",

    },
    {
        id:2,
        classname:"two",
        name:"Model 3",
        link:"/model3",
        img:"https://firebasestorage.googleapis.com/v0/b/the-tesla-clone.appspot.com/o/model-3.jpg?alt=media&token=03f2a148-33b7-4d58-b044-5c53072fbb64",
        description:"Order online for ",
        description2:"Touchless Delivery",
        leftBtnText:"Custom order",
        rightBtnText:"Existing Inventory",
        
    },
    {
        id:3,
        classname:"three",
        name:"Model X",
        link:"/modelx",
        img:"https://firebasestorage.googleapis.com/v0/b/the-tesla-clone.appspot.com/o/model-x.jpg?alt=media&token=65b69cee-81b5-4896-880b-78e7f80020d3",
        description:"Order online for ",
        description2:"Touchless Delivery",
        leftBtnText:"Custom order",
        rightBtnText:"Existing Inventory",
    },
    {
        id:4,
        classname:"four",
        name:"Model Y",
        link:"/modely",
        img:"https://firebasestorage.googleapis.com/v0/b/the-tesla-clone.appspot.com/o/model-y.jpg?alt=media&token=2882252c-6a0a-4524-a4d4-09244627d5c0",
        description:"Order online for ",
        description2:"Touchless Delivery",
        leftBtnText:"Custom order",
        rightBtnText:"Existing Inventory",
    },
    {
        id:5,
        classname:"five",
        name:"Solar Panels",
        link:"/solarpanel",
        img:"https://firebasestorage.googleapis.com/v0/b/the-tesla-clone.appspot.com/o/solar-panel.jpg?alt=media&token=6aa813c2-ff8e-43f5-b9c5-b075892bb02a",
        description:"Lowest Cost Solar Panels in America",
        leftBtnText:"Order Now",
        rightBtnText:"Learn More",

    },
    {
        id:6,
        classname:"six",
        name:"Solar Roof",
        link:"/solarroof",
        img:"https://firebasestorage.googleapis.com/v0/b/the-tesla-clone.appspot.com/o/solar-roof.jpg?alt=media&token=3a3acbac-00c2-41a1-b7e1-82d1c59edc4f",
        description:"Produce Clean Energy From Your Roof",
        leftBtnText:"Order Now",
        rightBtnText:"Learn More",
    },
    {
        id:7,
        classname:"seven",
        name:"Accessories",
        link:"#",
        img:"https://firebasestorage.googleapis.com/v0/b/the-tesla-clone.appspot.com/o/accessories.jpg?alt=media&token=463967da-3714-4fb6-bc34-f831bd9a9059",
        leftBtnText:"Shop Now",
    },
];